<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center>

<center> <h1>Curso : Computación 2</h1> </center>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

<center> <h1>Análisis de Datos con PANDAS</h1> </center>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

# Descripción:

<div class="alert alert-info">

En este notebook se explicarán Análisis de Datos con la librería **Pandas**  en el lenguaje de programación Python. 
    
</div>

# Objetivos:

 1. Importando archivos ***csv*** y manipulación inicial en **Pandas.**
 2. Analisis con datos reales de Futbol


[Análisis de Datos English Premier League (EPL)](#Análisis-de-Datos-English-Premier-League-(EPL)-2020-2021)<br>



[BIBLIOGRAFÍA](#BIBLIOGRAFÍA)<br>

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

<center><img src="https://futbolete.com/apuestas/wp-content/uploads/2021/01/premier-league.png" width="600" height="4200"></center>

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

<div class="alert alert-info"> La <strong>Premier League</strong>, también conocida en Inglaterra como The Premiership, es la máxima categoría del sistema de ligas de fútbol de Inglaterra. Comenzó a disputarse en la temporada 1992-93</div>

<div class="alert alert-info"> El análisis se realiza de la ultima temporada <strong>2020-2021</strong> de la <strong> Premier League</strong>

La Colección de datos utilizada de la temporada <strong>2020-2021</strong> de la <strong> Premier League</strong>
fueron descargados desde:

</div>

https://bit.ly/3aRnGVx

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****Análisis de Datos English Premier League (EPL) 2020-2021****<tfont>

In [1]:
#Librerías
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

Cargamos los **datos** para luego ***limpiar nuestros datos***.

In [2]:
#cargamos un archivo CSV separado por comas
epl = pd.read_csv('EPL_20_21.csv')

In [3]:
#leer 5 primeras lineas
epl.head()

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
0,Mason Mount,Chelsea,ENG,"MF,FW",21,36,32,2890,6,5,1881,82.3,1,1,0.21,0.24,2,0
1,Edouard Mendy,Chelsea,SEN,GK,28,31,31,2745,0,0,1007,84.6,0,0,0.00,0.00,2,0
2,Timo Werner,Chelsea,GER,FW,24,35,29,2602,6,8,826,77.2,0,0,0.41,0.21,2,0
3,Ben Chilwell,Chelsea,ENG,DF,23,27,27,2286,3,5,1806,78.6,0,0,0.10,0.11,3,0
4,Reece James,Chelsea,ENG,DF,20,32,25,2373,1,2,1987,85.0,0,0,0.06,0.12,3,0

In [4]:
#leer 4 primeras lineas aleatorias

epl.sample(4)

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards
426,Nick Pope,Burnley,ENG,GK,28,32,32,2880,0,0,979,50.7,0,0,0.00,0.01,1,0
115,James Maddison,Leicester City,ENG,"MF,FW",23,31,24,2099,8,5,1116,77.3,0,0,0.19,0.23,4,0
482,Dara O'Shea,West Bromwich Albion,IRL,DF,21,28,25,2102,0,0,857,66.0,0,0,0.01,0.01,3,0
194,Dani Ceballos,Arsenal,ESP,MF,23,25,17,1615,0,3,1286,86.5,0,0,0.04,0.16,4,0

In [5]:
#Información del DataFrame

epl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532 entries, 0 to 531
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   532 non-null    object
 1   Club                   532 non-null    object
 2   Nationality            532 non-null    object
 3   Position               532 non-null    object
 4   Age                    532 non-null    int64
 5   Matches                532 non-null    int64
 6   Starts                 532 non-null    int64
 7   Mins                   532 non-null    int64
 8   Goals                  532 non-null    int64
 9   Assists                532 non-null    int64
 10  Passes_Attempted       532 non-null    int64
 11  Perc_Passes_Completed  532 non-null    float64
 12  Penalty_Goals          532 non-null    int64
 13  Penalty_Attempted      532 non-null    int64
 14  xG                     532 non-null    float64
 15  xA                     532 non-null    float64
 16  Yellow_Cards           532 non-null    int64
 17  Red_Cards              532 non-null    int64
dtypes: float64(3), int64(11), object(4)
memory usage: 74.9+ KB

In [7]:
#Resumen de Datos estadisticos ---- Solo columnas numéricas

epl.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,532.0,25.500000,4.319404,16.0,22.00,26.00,29.000,38.00
Matches,532.0,19.535714,11.840459,1.0,9.00,21.00,30.000,38.00
Starts,532.0,15.714286,11.921161,0.0,4.00,15.00,27.000,38.00
Mins,532.0,1411.443609,1043.171856,1.0,426.00,1345.00,2303.500,3420.00
Goals,532.0,1.853383,3.338009,0.0,0.00,1.00,2.000,23.00
Assists,532.0,1.287594,2.095191,0.0,0.00,0.00,2.000,14.00
Passes_Attempted,532.0,717.750000,631.372522,0.0,171.50,573.50,1129.500,3214.00
Perc_Passes_Completed,532.0,77.823872,13.011631,-1.0,73.50,79.20,84.625,100.00
Penalty_Goals,532.0,0.191729,0.850881,0.0,0.00,0.00,0.000,9.00
Penalty_Attempted,532.0,0.234962,0.975818,0.0,0.00,0.00,0.000,10.00
xG,532.0,0.113289,0.148174,0.0,0.01,0.06,0.150,1.16
xA,532.0,0.072650,0.090072,0.0,0.00,0.05,0.110,0.90
Yellow_Cards,532.0,2.114662,2.269094,0.0,0.00,2.00,3.000,12.00
Red_Cards,532.0,0.090226,0.293268,0.0,0.00,0.00,0.000,2.00

In [8]:
#Número total de valores nulos

epl.isna().sum()

Name                     0
Club                     0
Nationality              0
Position                 0
Age                      0
Matches                  0
Starts                   0
Mins                     0
Goals                    0
Assists                  0
Passes_Attempted         0
Perc_Passes_Completed    0
Penalty_Goals            0
Penalty_Attempted        0
xG                       0
xA                       0
Yellow_Cards             0
Red_Cards                0
dtype: int64

Creamos 2 columnas mas **Minutos por partido** y ***Goles por partido***.

In [9]:
# creacion de 2 columnas

epl['MinsPerMatch']=(epl['Mins']/epl['Matches']).astype(int)
epl['GoalsPerMatch']=(epl['Goals']/epl['Matches']).astype(float)

In [10]:
#visualizamos las nuevas columnas
epl.head()

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards,MinsPerMatch,GoalsPerMatch
0,Mason Mount,Chelsea,ENG,"MF,FW",21,36,32,2890,6,5,1881,82.3,1,1,0.21,0.24,2,0,80,0.166667
1,Edouard Mendy,Chelsea,SEN,GK,28,31,31,2745,0,0,1007,84.6,0,0,0.00,0.00,2,0,88,0.000000
2,Timo Werner,Chelsea,GER,FW,24,35,29,2602,6,8,826,77.2,0,0,0.41,0.21,2,0,74,0.171429
3,Ben Chilwell,Chelsea,ENG,DF,23,27,27,2286,3,5,1806,78.6,0,0,0.10,0.11,3,0,84,0.111111
4,Reece James,Chelsea,ENG,DF,20,32,25,2373,1,2,1987,85.0,0,0,0.06,0.12,3,0,74,0.031250

In [11]:
#Total de goles ---- temporada EPL 2020-2021 ultima temporada

tgoles=epl['Penalty_Goals'].sum()
tgoles

102

In [12]:
#Goles x Penales ---- temporada EPL 2020-2021 ultima temporada


tgoles=epl['Penalty_Goals'].sum()
tgoles

102

In [19]:
# Total Penales ---- temporada EPL 2020-2021 ultima temporada

tgolesa=epl['Penalty_Attempted'].sum()
tgolesa

125

### Gráfico Pie chart **Penales Marcados** y **Penales Atajados**.

In [ ]:
# Gráficos de penales
plt.figure(figsize=(13,6))

In [20]:
# Posiciones únicas de cada jugador 
# Portero (GK), defensor (DF), centrocampista (MF) delantero (FW)


epl['Position'].unique()

array(['MF,FW', 'GK', 'FW', 'DF', 'MF', 'FW,MF', 'FW,DF', 'DF,MF',
       'MF,DF', 'DF,FW'], dtype=object)

In [24]:
# Filtrar jugadores delanteros (FW)

epl[epl['Position']=='FW']

,Name,Club,Nationality,Position,Age,Matches,Starts,Mins,Goals,Assists,Passes_Attempted,Perc_Passes_Completed,Penalty_Goals,Penalty_Attempted,xG,xA,Yellow_Cards,Red_Cards,MinsPerMatch,GoalsPerMatch
2,Timo Werner,Chelsea,GER,FW,24,35,29,2602,6,8,826,77.2,0,0,0.41,0.21,2,0,74,0.171429
16,Tammy Abraham,Chelsea,ENG,FW,22,22,12,1040,6,1,218,68.3,0,0,0.56,0.07,0,0,47,0.272727
19,Olivier Giroud,Chelsea,FRA,FW,33,17,8,748,4,0,217,74.2,0,0,0.58,0.09,1,0,44,0.235294
23,Ruben Loftus-Cheek,Chelsea,ENG,FW,24,1,1,60,0,0,16,68.8,0,0,0.00,0.00,0,0,60,0.000000
30,Raheem Sterling,Manchester City,ENG,FW,25,31,28,2536,10,7,1127,85.4,0,1,0.43,0.17,4,0,81,0.322581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,Oliver Burke,Sheffield United,SCO,FW,23,25,14,1269,1,1,262,70.6,0,0,0.17,0.13,2,0,50,0.040000
518,Oliver McBurnie,Sheffield United,SCO,FW,24,23,12,1324,1,0,426,62.9,0,0,0.21,0.07,2,0,57,0.043478
519,Rhian Brewster,Sheffield United,ENG,FW,20,27,12,1128,0,0,225,69.3,0,0,0.14,0.13,1,0,41,0.000000
523,Billy Sharp,Sheffield United,ENG,FW,34,16,7,735,3,0,123,69.9,2,2,0.33,0.07,1,0,45,0.187500
526,Daniel Jebbison,Sheffield United,ENG,FW,17,4,3,284,1,0,34,70.6,0,0,0.50,0.01,0,0,71,0.250000

In [27]:
# Cantidad jugadores delanteros (FW)

fw=epl[epl['Position']=='FW']
fw['GoalsPerMatch'].count()

81

In [28]:
#  Nacionalidad de los Jugadores


np.size((epl['Nationality'].unique()))

59

![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Guía de pandas oficial https://pandas.pydata.org/docs/user_guide/index.html

[2] Python Pandas Tutorial: A Complete Introduction for Beginners https://bit.ly/2AQMQld

[3] Guía para pandas https://pybonacci.org/2014/05/30/pandas-i/

[4] Dataset variados https://www.kaggle.com/datasets

[5] SimpliLearn https://www.youtube.com/c/SimplilearnOfficial

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)